### ISSUE TITLE
Npm scripts fail on Windows

### ISSUE THREAD

**Issue by patm2013** [sohelamin/electron-vue-boilerplate#2]
Getting a 'NODE_ENV' is not recognized as an internal or external command, when trying to run on Windows.

Solution is to go into package.json and change

`NODE_ENV=development`

to 

`SET NODE_ENV=development &`

**Comment by sohelamin** [comment]
Okay I'll check it on windows.

**Comment by sohelamin** [comment]
Hi Please check again.
Also I've upgraded Vue 1.0 to 2.0
