### ISSUE TITLE
Compatible with vue-cli?

### ISSUE THREAD

**Issue by atinux** [sohelamin/electron-vue-boilerplate#4]
Hi @sohelamin 

Great boilerplate :)

What do you think to make it compatible with [vue-cli](https://github.com/vuejs/vue-cli), so it would be possible to install it with:

``` bash
vue init sohelamin/electron-vue-boilerplate <project-name>
```

This way, the user have the possibility to answer few question and you can already fill some files with this informations (package.json) for example.

Tell me what do you think about it 😃

**Comment by sohelamin** [comment]
Great idea (y) @Atinux 
I will take care it when I will get some times.

**Comment by sohelamin** [comment]
Sorry for the late update.
You can use the template using `vue-cli` from now. https://github.com/sohelamin/electron-vue-boilerplate/tree/develop
And feel free to make PR if you like to 😄
