### ISSUE TITLE
npm run dev not working

### ISSUE THREAD

**Issue by mcicolella** [sohelamin/electron-vue-boilerplate#9]
Hi,
I created a project based on your template but when I execute 'npm run dev' electron shows a window as in the following image ("Welcome to ntopng")

![schermata del 2018-03-24 17-03-01](https://user-images.githubusercontent.com/4079634/37866212-c95548e8-2f87-11e8-97e3-1274f51a88f8.png)

@sohelamin any idea?

**Comment by sohelamin** [comment]
Hi, 
Try now that was issue with vue-cli.
I removed the vue-cli support.
